<option value="Afganistán">Afganistán</option>
<option value="Albania">Albania</option>
<option value="Alemania">Alemania</option>
<option value="Andorra">Andorra</option>
<option value="Angola">Angola</option>
<option value="Antigua y Barbuda">Antigua y Barbuda</option>
<option value="">Arabia Saudita</option>
<option value="">Argelia</option>
<option value="">Argentina</option>
<option value="">Armenia</option>
<option value="">Australia</option>
<option value="">Austria</option>
<option value="">Azerbaiyán</option>
<option value="">Bahamas</option>
<option value="">Bangladés</option>
<option value="">Barbados</option>
<option value="">Baréin</option>
<option value="">Bélgica</option>
<option value="">Belice</option>
<option value="">Benín</option>
<option value="">Bielorrusia</option>
<option value="">Birmania</option>
<option value="">Bolivia</option>
<option value="">Bosnia y Herzegovina</option>
<option value="">Botsuana</option>
<option value="">Brasil</option>
<option value="">Brunéi</option>
<option value="">Bulgaria</option>
<option value="">Burkina Faso</option>
<option value="">Burundi</option>
<option value="">Bután</option>
<option value="">Cabo Verde</option>
<option value="">Camboya</option>
<option value="">Camerún</option>
<option value="">Canadá</option>
<option value="">Catar</option>
<option value="">Chad</option>
<option value="">Chile</option>
<option value="">China</option>
<option value="">Chipre</option>
<option value="">Ciudad del Vaticano</option>
<option value="">Colombia</option>
<option value="">Comoras</option>
<option value="">Corea del Norte</option>
<option value="">Corea del Sur</option>
<option value="">Costa de Marfil</option>
<option value="">Costa Rica</option>
<option value="">Croacia</option>
<option value="">Cuba</option>
<option value="">Dinamarca</option>
<option value="">Dominica</option>
<option value="">Ecuador</option>
<option value="">Egipto</option>
<option value="">El Salvador</option>
<option value="">Emiratos Árabes Unidos</option>
<option value="">Eritrea</option>
<option value="">Eslovaquia</option>
<option value="">Eslovenia</option>
<option value="">España</option>
<option value="">Estados Unidos</option>
<option value="">Estonia</option>
<option value="">Etiopía</option>
<option value="">Filipinas</option>
<option value="">Finlandia</option>
<option value="">Fiyi</option>
<option value="">Francia</option>
<option value="">Gabón</option>
<option value="">Gambia</option>
<option value="">Georgia</option>
<option value="">Ghana</option>
<option value="">Granada</option>
<option value="">Grecia</option>
<option value="">Guatemala</option>
<option value="">Guyana</option>
<option value="">Guinea</option>
<option value="">Guinea ecuatorial</option>
<option value="">Guinea-Bisáu</option>
<option value="">Haití</option>
<option value="">Honduras</option>
<option value="">Hungría</option>
<option value="">India</option>
<option value="">Indonesia</option>
<option value="">Irak</option>
<option value="">Irán</option>
<option value="">Irlanda</option>
<option value="">Islandia</option>
<option value="">Islas Marshall</option>
<option value="">Islas Salomón</option>
<option value="">Israel</option>
<option value="">Italia</option>
<option value="">Jamaica</option>
<option value="">Japón</option>
<option value="">Jordania</option>
<option value="">Kazajistán</option>
<option value="">Kenia</option>
<option value="">Kirguistán</option>
<option value="">Kiribati</option>
<option value="">Kuwait</option>
<option value="">Laos</option>
<option value="">Lesoto</option>
<option value="">Letonia</option>
<option value="">Líbano</option>
<option value="">Liberia</option>
<option value="">Libia</option>
<option value="">Liechtenstein</option>
<option value="">Lituania</option>
<option value="">Luxemburgo</option>
<option value="">Macedonia del Norte</option>
<option value="">Madagascar</option>
<option value="">Malasia</option>
<option value="">Malaui</option>
<option value="">Maldivas</option>
<option value="">Malí</option>
<option value="">Malta</option>
<option value="">Marruecos</option>
<option value="">Mauricio</option>
<option value="">Mauritania</option>
<option value="">México</option>
<option value="">Micronesia</option>
<option value="">Moldavia</option>
<option value="">Mónaco</option>
<option value="">Mongolia</option>
<option value="">Montenegro</option>
<option value="">Mozambique</option>
<option value="">Namibia</option>
<option value="">Nauru</option>
<option value="">Nepal</option>
<option value="">Nicaragua</option>
<option value="">Níger</option>
<option value="">Nigeria</option>
<option value="">Noruega</option>
<option value="">Nueva Zelanda</option>
<option value="">Omán</option>
<option value="">Países Bajos</option>
<option value="">Pakistán</option>
<option value="">Palaos</option>
<option value="">Panamá</option>
<option value="">Papúa Nueva Guinea</option>
<option value="">Paraguay</option>
<option value="">Perú</option>
<option value="">Polonia</option>
<option value="">Portugal</option>
<option value="">Reino Unido</option>
<option value="">República Centroafricana</option>
<option value="">República Checa</option>
<option value="">República del Congo</option>
<option value="">República Democrática del Congo</option>
<option value="">República Dominicana</option>
<option value="">Ruanda</option>
<option value="">Rumanía</option>
<option value="">Rusia</option>
<option value="">Samoa</option>
<option value="">San Cristóbal y Nieves</option>
<option value="">San Marino</option>
<option value="">San Vicente y las Granadinas</option>
<option value="">Santa Lucía</option>
<option value="">Santo Tomé y Príncipe</option>
<option value="">Senegal</option>
<option value="">Serbia</option>
<option value="">Seychelles</option>
<option value="">Sierra Leona</option>
<option value="">Singapur</option>
<option value="">Siria</option>
<option value="">Somalia</option>
<option value="">Sri Lanka</option>
<option value="">Suazilandia</option>
<option value="">Sudáfrica</option>
<option value="">Sudán</option>
<option value="">Sudán del Sur</option>
<option value="">Suecia</option>
<option value="">Suiza</option>
<option value="">Surinam</option>
<option value="">Tailandia</option>
<option value="">Tanzania</option>
<option value="">Tayikistán</option>
<option value="">Timor Oriental</option>
<option value="">Togo</option>
<option value="">Tonga</option>
<option value="">Trinidad y Tobago</option>
<option value="">Túnez</option>
<option value="">Turkmenistán</option>
<option value="">Turquía</option>
<option value="">Tuvalu</option>
<option value="">Ucrania</option>
<option value="">Uganda</option>
<option value="">Uruguay</option>
<option value="">Uzbekistán</option>
<option value="">Vanuatu</option>
<option value="">Venezuela</option>
<option value="">Vietnam</option>
<option value="">Yemen</option>
<option value="">Yibuti</option>
<option value="">Zambia</option>
<option value="">Zimbabue</option>